<?php


namespace Test;


class TestCase extends \PHPUnit\Framework\TestCase
{
    public function tearDown(): void
    {
        \Mockery::close();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}